<template>
  <demo-sample-panel :title="anchor.title" :panel-id="anchor.id">
    <ul class="boss-icons">
      <li class="boss-icons__item" v-for="icon in icons" :key="icon">
        <i :class="icon"></i>
        <span class="boss-icons__item-name">{{icon}}</span>
      </li>
    </ul>
  </demo-sample-panel>
</template>
<script>
import code from "./code";
export default {
  mixins: [code],
  data() {
    return {
      icons: [
        "boss-icon-delete-solid",
        "boss-icon-delete",
        "boss-icon-s-tools",
        "boss-icon-setting",
        "boss-icon-user-solid",
        "boss-icon-user",
        "boss-icon-phone",
        "boss-icon-phone-outline",
        "boss-icon-more",
        "boss-icon-more-outline",
        "boss-icon-star-on",
        "boss-icon-star-off",
        "boss-icon-s-goods",
        "boss-icon-goods",
        "boss-icon-warning",
        "boss-icon-warning-outline",
        "boss-icon-question",
        "boss-icon-info",
        "boss-icon-remove",
        "boss-icon-circle-plus",
        "boss-icon-success",
        "boss-icon-error",
        "boss-icon-zoom-in",
        "boss-icon-zoom-out",
        "boss-icon-remove-outline",
        "boss-icon-circle-plus-outline",
        "boss-icon-circle-check",
        "boss-icon-circle-close",
        "boss-icon-s-help",
        "boss-icon-help",
        "boss-icon-minus",
        "boss-icon-plus",
        "boss-icon-check",
        "boss-icon-close",
        "boss-icon-picture",
        "boss-icon-picture-outline",
        "boss-icon-picture-outline-round",
        "boss-icon-upload",
        "boss-icon-upload2",
        "boss-icon-download",
        "boss-icon-camera-solid",
        "boss-icon-camera",
        "boss-icon-video-camera-solid",
        "boss-icon-video-camera",
        "boss-icon-message-solid",
        "boss-icon-bell",
        "boss-icon-s-cooperation",
        "boss-icon-s-order",
        "boss-icon-s-platform",
        "boss-icon-s-fold",
        "boss-icon-s-unfold",
        "boss-icon-s-operation",
        "boss-icon-s-promotion",
        "boss-icon-s-home",
        "boss-icon-s-release",
        "boss-icon-s-ticket",
        "boss-icon-s-management",
        "boss-icon-s-open",
        "boss-icon-s-shop",
        "boss-icon-s-marketing",
        "boss-icon-s-flag",
        "boss-icon-s-comment",
        "boss-icon-s-finance",
        "boss-icon-s-claim",
        "boss-icon-s-custom",
        "boss-icon-s-opportunity",
        "boss-icon-s-data",
        "boss-icon-s-check",
        "boss-icon-s-grid",
        "boss-icon-menu",
        "boss-icon-share",
        "boss-icon-d-caret",
        "boss-icon-caret-left",
        "boss-icon-caret-right",
        "boss-icon-caret-bottom",
        "boss-icon-caret-top",
        "boss-icon-bottom-left",
        "boss-icon-bottom-right",
        "boss-icon-back",
        "boss-icon-right",
        "boss-icon-bottom",
        "boss-icon-top",
        "boss-icon-top-left",
        "boss-icon-top-right",
        "boss-icon-arrow-left",
        "boss-icon-arrow-right",
        "boss-icon-arrow-down",
        "boss-icon-arrow-up",
        "boss-icon-d-arrow-left",
        "boss-icon-d-arrow-right",
        "boss-icon-video-pause",
        "boss-icon-video-play",
        "boss-icon-refresh",
        "boss-icon-refresh-right",
        "boss-icon-refresh-left",
        "boss-icon-finished",
        "boss-icon-sort",
        "boss-icon-sort-up",
        "boss-icon-sort-down",
        "boss-icon-rank",
        "boss-icon-loading",
        "boss-icon-view",
        "boss-icon-c-scale-to-original",
        "boss-icon-date",
        "boss-icon-edit",
        "boss-icon-edit-outline",
        "boss-icon-folder",
        "boss-icon-folder-opened",
        "boss-icon-folder-add",
        "boss-icon-folder-remove",
        "boss-icon-folder-delete",
        "boss-icon-folder-checked",
        "boss-icon-tickets",
        "boss-icon-document-remove",
        "boss-icon-document-delete",
        "boss-icon-document-copy",
        "boss-icon-document-checked",
        "boss-icon-document",
        "boss-icon-document-add",
        "boss-icon-printer",
        "boss-icon-paperclip",
        "boss-icon-takeaway-box",
        "boss-icon-search",
        "boss-icon-monitor",
        "boss-icon-attract",
        "boss-icon-mobile",
        "boss-icon-scissors",
        "boss-icon-umbrella",
        "boss-icon-headset",
        "boss-icon-brush",
        "boss-icon-mouse",
        "boss-icon-coordinate",
        "boss-icon-magic-stick",
        "boss-icon-reading",
        "boss-icon-data-line",
        "boss-icon-data-board",
        "boss-icon-pie-chart",
        "boss-icon-data-analysis",
        "boss-icon-collection-tag",
        "boss-icon-film",
        "boss-icon-suitcase",
        "boss-icon-suitcase-1",
        "boss-icon-receiving",
        "boss-icon-collection",
        "boss-icon-files",
        "boss-icon-notebook-1",
        "boss-icon-notebook-2",
        "boss-icon-toilet-paper",
        "boss-icon-office-building",
        "boss-icon-school",
        "boss-icon-table-lamp",
        "boss-icon-house",
        "boss-icon-no-smoking",
        "boss-icon-smoking",
        "boss-icon-shopping-cart-full",
        "boss-icon-shopping-cart-1",
        "boss-icon-shopping-cart-2",
        "boss-icon-shopping-bag-1",
        "boss-icon-shopping-bag-2",
        "boss-icon-sold-out",
        "boss-icon-sell",
        "boss-icon-present",
        "boss-icon-box",
        "boss-icon-bank-card",
        "boss-icon-money",
        "boss-icon-coin",
        "boss-icon-wallet",
        "boss-icon-discount",
        "boss-icon-price-tag",
        "boss-icon-news",
        "boss-icon-guide",
        "boss-icon-male",
        "boss-icon-female",
        "boss-icon-thumb",
        "boss-icon-cpu",
        "boss-icon-link",
        "boss-icon-connection",
        "boss-icon-open",
        "boss-icon-turn-off",
        "boss-icon-set-up",
        "boss-icon-chat-round",
        "boss-icon-chat-line-round",
        "boss-icon-chat-square",
        "boss-icon-chat-dot-round",
        "boss-icon-chat-dot-square",
        "boss-icon-chat-line-square",
        "boss-icon-message",
        "boss-icon-postcard",
        "boss-icon-position",
        "boss-icon-turn-off-microphone",
        "boss-icon-microphone",
        "boss-icon-close-notification",
        "boss-icon-bangzhu",
        "boss-icon-time",
        "boss-icon-odometer",
        "boss-icon-crop",
        "boss-icon-aim",
        "boss-icon-switch-button",
        "boss-icon-full-screen",
        "boss-icon-copy-document",
        "boss-icon-mic",
        "boss-icon-stopwatch",
        "boss-icon-medal-1",
        "boss-icon-medal",
        "boss-icon-trophy",
        "boss-icon-trophy-1",
        "boss-icon-first-aid-kit",
        "boss-icon-discover",
        "boss-icon-place",
        "boss-icon-location",
        "boss-icon-location-outline",
        "boss-icon-location-information",
        "boss-icon-add-location",
        "boss-icon-delete-location",
        "boss-icon-map-location",
        "boss-icon-alarm-clock",
        "boss-icon-timer",
        "boss-icon-watch-1",
        "boss-icon-watch",
        "boss-icon-lock",
        "boss-icon-unlock",
        "boss-icon-key",
        "boss-icon-service",
        "boss-icon-mobile-phone",
        "boss-icon-bicycle",
        "boss-icon-truck",
        "boss-icon-ship",
        "boss-icon-basketball",
        "boss-icon-football",
        "boss-icon-soccer",
        "boss-icon-baseball",
        "boss-icon-wind-power",
        "boss-icon-light-rain",
        "boss-icon-lightning",
        "boss-icon-heavy-rain",
        "boss-icon-sunrise",
        "boss-icon-sunrise-1",
        "boss-icon-sunset",
        "boss-icon-sunny",
        "boss-icon-cloudy",
        "boss-icon-partly-cloudy",
        "boss-icon-cloudy-and-sunny",
        "boss-icon-moon",
        "boss-icon-moon-night",
        "boss-icon-dish",
        "boss-icon-dish-1",
        "boss-icon-food",
        "boss-icon-chicken",
        "boss-icon-fork-spoon",
        "boss-icon-knife-fork",
        "boss-icon-burger",
        "boss-icon-tableware",
        "boss-icon-sugar",
        "boss-icon-dessert",
        "boss-icon-ice-cream",
        "boss-icon-hot-water",
        "boss-icon-water-cup",
        "boss-icon-coffee-cup",
        "boss-icon-cold-drink",
        "boss-icon-goblet",
        "boss-icon-goblet-full",
        "boss-icon-goblet-square",
        "boss-icon-goblet-square-full",
        "boss-icon-refrigerator",
        "boss-icon-grape",
        "boss-icon-watermelon",
        "boss-icon-cherry",
        "boss-icon-apple",
        "boss-icon-pear",
        "boss-icon-orange",
        "boss-icon-coffee",
        "boss-icon-ice-tea",
        "boss-icon-ice-drink",
        "boss-icon-milk-tea",
        "boss-icon-potato-strips",
        "boss-icon-lollipop",
        "boss-icon-ice-cream-square",
        "boss-icon-ice-cream-round"
      ]
    };
  }
};
</script>
<style lang="scss" scoped>
.boss-icons {
  overflow: hidden;
  border-top: 1px solid #eee;
  border-left: 1px solid #eee;
  &__item {
    list-style: none;
    box-sizing: border-box;
    border-bottom: 1px solid #eee;
    border-right: 1px solid #eee;
    text-align: center;
    height: 120px;
    cursor: pointer;
    &:hover{
      i,span {
        color: #5cb6ff
      }
    }
    float: left;
    width: 16.66%;
    i {
      font-size: 32px;
      color: #606266;
      transition: color 0.15s linear;
      margin-bottom: 15px;
      margin-top: 25px;
    }
    &-name {
      color: #99a9bf;
      display: block;
      font-size: 13px;
      padding: 0 2px;
    }
  }
}
</style>